// src/lib/providers/provider-presets.ts
//
// Structured provider preset registry containing popular direct model providers,
// routers/gateways, local servers, and custom configurations.

import type { PresetDefinition } from "./types";

export const PRESETS: PresetDefinition[] = [
  // ============================================================================
  // POPULAR PROVIDERS
  // ============================================================================
  {
    id: "openai",
    label: "OpenAI",
    providerType: "openai",
    protocol: "openai-compatible",
    baseUrl: "https://api.openai.com/v1",
    defaultModel: "gpt-4o",
    description: "Official OpenAI developer API. Fast, standard, and highly capable.",
    companyName: "OpenAI",
    category: "popular",
    apiStyle: "openai-compatible",
    docsUrl: "https://platform.openai.com/docs",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "openai",
    shortDescription: "Official OpenAI API platform",
    setupHint: "Requires an API key starting with 'sk-'.",
    isPopular: true,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "gemini",
    label: "Google Gemini",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    defaultModel: "gemini-2.5-flash",
    description: "Google's Gemini models via the OpenAI compatibility API wrapper.",
    companyName: "Google",
    category: "popular",
    apiStyle: "openai-compatible",
    docsUrl: "https://ai.google.dev/gemini-api/docs/openai",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "gemini",
    shortDescription: "Google's Gemini models via OpenAI compatibility API",
    setupHint: "Get your API key from Google AI Studio.",
    isPopular: true,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    providerType: "openrouter",
    protocol: "openai-compatible",
    baseUrl: "https://openrouter.ai/api/v1",
    defaultModel: "meta-llama/llama-3.3-70b-instruct:free",
    description: "Unified router offering access to hundreds of open-source and proprietary models.",
    companyName: "OpenRouter",
    category: "popular",
    apiStyle: "openai-compatible",
    docsUrl: "https://openrouter.ai/docs",
    authHeaderType: "bearer",
    modelDiscoveryType: "openrouter",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "openrouter",
    shortDescription: "Multi-provider LLM gateway and router",
    setupHint: "Create an API key on openrouter.ai.",
    isPopular: true,
    isRouter: true,
    isDirectProvider: false,
  },
  {
    id: "anthropic",
    label: "Anthropic Claude",
    providerType: "anthropic",
    protocol: "anthropic-compatible",
    baseUrl: "https://api.anthropic.com/v1",
    defaultModel: "claude-3-5-sonnet-latest",
    description: "Anthropic's Claude models. High reasoning and context capacities.",
    companyName: "Anthropic",
    category: "popular",
    apiStyle: "anthropic-compatible",
    docsUrl: "https://docs.anthropic.com",
    authHeaderType: "custom",
    modelDiscoveryType: "none",
    supportsStreaming: true,
    supportsCustomModels: false,
    logoKey: "anthropic",
    shortDescription: "Anthropic's Claude foundation models",
    setupHint: "Requires a Claude API key.",
    isPopular: true,
    isRouter: false,
    isDirectProvider: true,
    disabled: true,
    disabledReason: "Anthropic API style is not implemented yet in the streaming engine.",
  },

  // ============================================================================
  // DIRECT PROVIDERS
  // ============================================================================
  {
    id: "deepseek",
    label: "DeepSeek",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://api.deepseek.com",
    defaultModel: "deepseek-chat",
    description: "DeepSeek developer API. Highly cost-effective intelligence and coding capabilities.",
    companyName: "DeepSeek",
    category: "direct",
    apiStyle: "openai-compatible",
    docsUrl: "https://api-docs.deepseek.com",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "deepseek",
    shortDescription: "High-performance cost-effective developer models",
    setupHint: "Generate an API key in your DeepSeek dashboard.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "groq",
    label: "Groq",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://api.groq.com/openai/v1",
    defaultModel: "llama-3.3-70b-versatile",
    description: "Groq LPU platform. Ultra low latency open weights inference server.",
    companyName: "Groq",
    category: "direct",
    apiStyle: "openai-compatible",
    docsUrl: "https://console.groq.com/docs",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "groq",
    shortDescription: "Ultra low latency LLM hosting",
    setupHint: "Generate an API key in the Groq console.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "mistral",
    label: "Mistral AI",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://api.mistral.ai/v1",
    defaultModel: "mistral-large-latest",
    description: "Mistral AI's developer endpoint. Specialized multilingual and coding models.",
    companyName: "Mistral",
    category: "direct",
    apiStyle: "openai-compatible",
    docsUrl: "https://docs.mistral.ai",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "mistral",
    shortDescription: "Mistral foundation and coding models",
    setupHint: "Generate an API key in Mistral console.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "together",
    label: "Together AI",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://api.together.xyz/v1",
    defaultModel: "meta-llama/Llama-3.3-70b-Instruct-Turbo",
    description: "Serverless endpoints for popular open weights and fine-tuned models.",
    companyName: "Together AI",
    category: "direct",
    apiStyle: "openai-compatible",
    docsUrl: "https://docs.together.ai",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "together",
    shortDescription: "High speed open source model endpoints",
    setupHint: "Get your key from together.ai console.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "xai",
    label: "xAI (Grok)",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://api.x.ai/v1",
    defaultModel: "grok-2",
    description: "xAI Grok developer platform. High reasoning capacities and system-context integrations.",
    companyName: "xAI",
    category: "direct",
    apiStyle: "openai-compatible",
    docsUrl: "https://docs.x.ai",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "xai",
    shortDescription: "xAI Grok developer API",
    setupHint: "Generate keys in the xAI developer portal.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "perplexity",
    label: "Perplexity AI",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://api.perplexity.ai",
    defaultModel: "sonar-reasoning",
    description: "Perplexity search model serving. Real-time web-grounded research answers.",
    companyName: "Perplexity",
    category: "direct",
    apiStyle: "openai-compatible",
    docsUrl: "https://docs.perplexity.ai",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "perplexity",
    shortDescription: "Search-grounded answer engine API",
    setupHint: "Configure billing and API keys on Perplexity.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "nvidia",
    label: "Nvidia NIM",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    defaultModel: "meta/llama-3.3-70b-instruct",
    description: "Nvidia API Catalog. Serving optimized foundation models on NVIDIA acceleration stacks.",
    companyName: "Nvidia",
    category: "direct",
    apiStyle: "openai-compatible",
    docsUrl: "https://docs.nvidia.com",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "nvidia",
    shortDescription: "Accelerated serverless NIM catalog",
    setupHint: "Requires a key from Nvidia Build portal.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "fireworks",
    label: "Fireworks AI",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    defaultModel: "accounts/fireworks/models/llama-v3p3-70b-instruct",
    description: "High-performance curated open weights model serving and fine-tuning hosts.",
    companyName: "Fireworks",
    category: "direct",
    apiStyle: "openai-compatible",
    docsUrl: "https://docs.fireworks.ai",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "fireworks",
    shortDescription: "Fast serverless inference engine",
    setupHint: "Get your key from fireworks.ai.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "cohere",
    label: "Cohere",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://api.cohere.com/v1",
    defaultModel: "command-r-plus",
    description: "Cohere developer API. Specialized enterprise chat, retrieval, and search tools.",
    companyName: "Cohere",
    category: "direct",
    apiStyle: "openai-compatible",
    docsUrl: "https://docs.cohere.com",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "cohere",
    shortDescription: "Enterprise LLM and search solutions",
    setupHint: "Generate keys in the Cohere dashboard.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "cerebras",
    label: "Cerebras",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://api.cerebras.ai/v1",
    defaultModel: "llama3.3-70b",
    description: "Cerebras Wafer-Scale Engine serverless API. Near-instantaneous response times.",
    companyName: "Cerebras",
    category: "direct",
    apiStyle: "openai-compatible",
    docsUrl: "https://docs.cerebras.ai",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "cerebras",
    shortDescription: "Extreme speed serverless LLM serve",
    setupHint: "Create a Cerebras API key in their developer portal.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "moonshot",
    label: "Moonshot AI",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://api.moonshot.cn/v1",
    defaultModel: "moonshot-v1-8k",
    description: "Moonshot Kimi developer portal. Extremely large context and Chinese-centric capacities.",
    companyName: "Moonshot",
    category: "direct",
    apiStyle: "openai-compatible",
    docsUrl: "https://platform.moonshot.cn",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "moonshot",
    shortDescription: "Moonshot AI / Kimi developer API",
    setupHint: "Generate an API key in Moonshot platform.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "minimax",
    label: "MiniMax",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://api.minimax.chat/v1",
    defaultModel: "MiniMax-Text-01",
    description: "MiniMax developer API. Multilingual, expressive, and high-throughput text models.",
    companyName: "MiniMax",
    category: "direct",
    apiStyle: "openai-compatible",
    docsUrl: "https://platform.minimaxi.com",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "minimax",
    shortDescription: "MiniMax developer model endpoints",
    setupHint: "Create an API key in MiniMax platform.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "ai21",
    label: "AI21 Studio",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://api.ai21.com/studio/v1/openai",
    defaultModel: "jamba-1-5-large",
    description: "AI21 Jurassic and Jamba hybrid models. Large context windows and fast inference speeds.",
    companyName: "AI21",
    category: "direct",
    apiStyle: "openai-compatible",
    docsUrl: "https://docs.ai21.com",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "ai21",
    shortDescription: "AI21 Jurassic/Jamba developer platform",
    setupHint: "Create keys in AI21 developer platform.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "aleph-alpha",
    label: "Aleph Alpha",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://api.aleph-alpha.com",
    defaultModel: "luminous-base",
    description: "European sovereign foundation model serving. Requires custom request formats.",
    companyName: "Aleph Alpha",
    category: "direct",
    apiStyle: "openai-compatible",
    logoKey: "alephalpha",
    shortDescription: "European sovereign LLMs",
    setupHint: "Aleph Alpha is not fully supported by standard chat streaming.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
    disabled: true,
    disabledReason: "Aleph Alpha requires a custom API style not currently supported.",
  },
  {
    id: "voyage",
    label: "Voyage AI",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://api.voyageai.com/v1",
    defaultModel: "voyage-3",
    description: "Specialized text embedding and reranker model serving.",
    companyName: "Voyage AI",
    category: "direct",
    apiStyle: "openai-compatible",
    logoKey: "voyage",
    shortDescription: "Text embedding & retrieval models",
    setupHint: "Voyage AI does not serve chat models.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
    disabled: true,
    disabledReason: "Voyage AI focuses on embeddings rather than chat completions.",
  },
  {
    id: "replicate",
    label: "Replicate",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://api.replicate.com/v1",
    defaultModel: "meta/meta-llama-3-70b-instruct",
    description: "Serverless execution for thousands of open-source models.",
    companyName: "Replicate",
    category: "direct",
    apiStyle: "openai-compatible",
    logoKey: "replicate",
    shortDescription: "Serverless model hosting and runs",
    setupHint: "Replicate uses custom run polling APIs.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
    disabled: true,
    disabledReason: "Replicate requires a custom request format not supported by the chat client.",
  },

  // ============================================================================
  // ROUTERS AND GATEWAYS
  // ============================================================================
  {
    id: "tokenrouter",
    label: "TokenRouter",
    providerType: "tokenrouter",
    protocol: "openai-compatible",
    baseUrl: "https://api.tokenrouter.com/v1",
    defaultModel: "MiniMax-M3",
    description: "TokenRouter chat API endpoint. High throughput multi-routing and failovers.",
    companyName: "TokenRouter",
    category: "router",
    apiStyle: "openai-compatible",
    docsUrl: "https://tokenrouter.com",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "tokenrouter",
    shortDescription: "Unified multi-vendor proxy and router",
    setupHint: "Input your TokenRouter secret key.",
    isPopular: false,
    isRouter: true,
    isDirectProvider: false,
  },
  {
    id: "litellm",
    label: "LiteLLM Proxy",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "http://localhost:4000/v1",
    defaultModel: "",
    description: "LiteLLM local proxy to manage credentials, tracking, and fallback setups.",
    companyName: "LiteLLM",
    category: "router",
    apiStyle: "openai-compatible",
    docsUrl: "https://docs.litellm.ai",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "litellm",
    shortDescription: "Local multi-provider proxy gateway",
    setupHint: "Assumes a running LiteLLM instance. Input bearer key if configured.",
    isPopular: false,
    isRouter: true,
    isDirectProvider: false,
  },
  {
    id: "portkey",
    label: "Portkey Gateway",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://api.portkey.ai/v1",
    defaultModel: "",
    description: "Portkey AI Gateway to route, monitor, log, and load-balance requests across providers.",
    companyName: "Portkey",
    category: "router",
    apiStyle: "openai-compatible",
    docsUrl: "https://docs.portkey.ai",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "portkey",
    shortDescription: "AI Gateway and observability proxy",
    setupHint: "Input Portkey API key or virtual keys.",
    isPopular: false,
    isRouter: true,
    isDirectProvider: false,
  },
  {
    id: "helicone",
    label: "Helicone Gateway",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "https://gateway.helicone.ai/v1",
    defaultModel: "",
    description: "Helicone AI proxy gateway for analytics, caching, and rate limiting.",
    companyName: "Helicone",
    category: "router",
    apiStyle: "openai-compatible",
    docsUrl: "https://docs.helicone.ai",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "helicone",
    shortDescription: "LLM observability proxy gateway",
    setupHint: "Requires a Helicone API key in headers.",
    isPopular: false,
    isRouter: true,
    isDirectProvider: false,
  },

  // ============================================================================
  // LOCAL/SELF-HOSTED
  // ============================================================================
  {
    id: "ollama",
    label: "Ollama (Local)",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "http://localhost:11434/v1",
    defaultModel: "llama3",
    description: "Local model server for running LLMs on your personal machine.",
    companyName: "Ollama",
    category: "local",
    apiStyle: "openai-compatible",
    docsUrl: "https://github.com/ollama/ollama",
    authHeaderType: "none",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "ollama",
    shortDescription: "Run open source models locally",
    setupHint: "Make sure Ollama is running. No API key required (enter any dummy text if required).",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "lm-studio",
    label: "LM Studio (Local)",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "http://localhost:1234/v1",
    defaultModel: "",
    description: "Local model serving application using OpenAI-compatible endpoints.",
    companyName: "LM Studio",
    category: "local",
    apiStyle: "openai-compatible",
    docsUrl: "https://lmstudio.ai",
    authHeaderType: "none",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "lmstudio",
    shortDescription: "Local model serving application",
    setupHint: "Start the Local Server inside LM Studio. No API key needed.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "localai",
    label: "LocalAI (Local)",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "http://localhost:8080/v1",
    defaultModel: "",
    description: "Self-hosted OpenAI-compatible local API for CPU/GPU.",
    companyName: "LocalAI",
    category: "local",
    apiStyle: "openai-compatible",
    docsUrl: "https://localai.io",
    authHeaderType: "none",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "localai",
    shortDescription: "Self-hosted OpenAI-compatible local API",
    setupHint: "Requires a running LocalAI container. Key not required by default.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "vllm",
    label: "vLLM Server (Local/Remote)",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "http://localhost:8000/v1",
    defaultModel: "",
    description: "High-throughput and memory-efficient local LLM serving engine.",
    companyName: "vLLM",
    category: "local",
    apiStyle: "openai-compatible",
    docsUrl: "https://docs.vllm.ai",
    authHeaderType: "none",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "vllm",
    shortDescription: "High-throughput serving engine",
    setupHint: "Start vLLM server with --api-key if security is required.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },
  {
    id: "llamacpp",
    label: "llama.cpp Server (Local)",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "http://localhost:8080/v1",
    defaultModel: "",
    description: "Ultra-lightweight local C/C++ model serving endpoint.",
    companyName: "llama.cpp",
    category: "local",
    apiStyle: "openai-compatible",
    docsUrl: "https://github.com/ggerganov/llama.cpp",
    authHeaderType: "none",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "llamacpp",
    shortDescription: "C/C++ foundation weights serving",
    setupHint: "Assumes running './server' binary. Dummy key can be entered.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: true,
  },

  // ============================================================================
  // CUSTOM
  // ============================================================================
  {
    id: "custom-openai",
    label: "Custom OpenAI-compatible",
    providerType: "custom",
    protocol: "openai-compatible",
    baseUrl: "",
    defaultModel: "",
    description: "Specify your own OpenAI-compatible endpoint URL and custom model configurations.",
    companyName: "Generic",
    category: "custom",
    apiStyle: "openai-compatible",
    authHeaderType: "bearer",
    modelDiscoveryType: "v1-models",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "custom",
    shortDescription: "Custom compatible API base",
    setupHint: "Provide the base URL and endpoint details manually below.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: false,
  },
  {
    id: "custom-anthropic",
    label: "Custom Anthropic-compatible",
    providerType: "custom",
    protocol: "anthropic-compatible",
    baseUrl: "",
    defaultModel: "",
    description: "Specify your own Anthropic-compatible Messages API endpoint.",
    companyName: "Generic",
    category: "custom",
    apiStyle: "anthropic-compatible",
    authHeaderType: "custom",
    modelDiscoveryType: "none",
    supportsStreaming: true,
    supportsCustomModels: true,
    logoKey: "custom",
    shortDescription: "Custom Anthropic API base",
    setupHint: "Provide the base URL and endpoint details manually below.",
    isPopular: false,
    isRouter: false,
    isDirectProvider: false,
    disabled: true,
    disabledReason: "Anthropic API style is not implemented yet in the streaming engine.",
  },
];
